import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { POST as create } from '../src/app/api/projects/route';
import { POST as action } from '../src/app/api/projects/[id]/action/route';
import { GET as download } from '../src/app/api/projects/[id]/download/route';
import { GET as read, PUT as update } from '../src/app/api/projects/[id]/route';
import { getProject } from '../src/lib/factory/store';
process.env.FACTORY_DATA_PATH=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'factory-route-')),'state.json');
const req=(body:unknown)=>new Request('http://localhost/api/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
test('API creates client, validates actions and downloads a real ZIP',async()=>{assert.equal((await create(req({businessProfile:{}}))).status,400);const response=await create(req({businessProfile:{name:'API Test Plumbing',url:'',industry:'Plumbing',city:'Tampa',services:['Drain cleaning'],primaryGoal:'More qualified leads'}}));assert.equal(response.status,201);let p=(await response.json()).project;const context={params:Promise.resolve({id:p.id})};const act=async(d:unknown)=>action(req(d),context);
 assert.equal((await act({action:'approve',assetId:'outreach-email'})).status,400);
 assert.equal((await act({action:'source',sourceId:p.sources[0].id})).status,200);
 assert.equal((await act({action:'regenerate',assetId:'outreach-email'})).status,200);
 assert.equal((await act({action:'approve',assetId:'outreach-email'})).status,200);
 assert.equal((await act({action:'save',assetId:'outreach-email',version:0,body:'Stale'})).status,409);
 assert.equal((await act({action:'run',evidence:'fake'})).status,400);
 assert.equal((await act({action:'result',metric:'Leads',baseline:0,current:5,period:'Week 1 vs Week 2',source:'Test fixture'})).status,200);
 p=getProject(p.id)!;const fact=p.factLocks.find((f:any)=>f.field==='name');await act({action:'fact',factId:fact.id});
 assert.equal((await update(req({businessProfile:{...p.businessProfile,name:'Changed'}}),context)).status,409);
 const skill=p.assets.find((a:any)=>a.kind==='skill');assert.equal((await act({action:'save',assetId:skill.id,version:skill.version,body:skill.body.replaceAll(p.name,'Another Name'),owner:'Operator',nextAction:'Review'})).status,409);
 const archive=await download(new Request('http://localhost/api/download?format=zip'),context);assert.equal(archive.status,200);const bytes=new Uint8Array(await archive.arrayBuffer());assert.equal(String.fromCharCode(bytes[0],bytes[1]),'PK');
 assert.equal((await read(new Request('http://localhost'),{params:Promise.resolve({id:'missing'})})).status,404);
});
