'use client';
import {useEffect,useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {X,Upload,Download,RotateCcw,Send,ArrowRight} from 'lucide-react';
import {fields,presets,parseCSV,guessHeaders,exportCSV,mappedValues,type Mapping,type Assessment} from '@/lib/campaign/model';
import {api,download} from './helpers';
export function CRMModal({assessment,notify}:{assessment:Assessment;notify:(s:string)=>void}){const [open,setOpen]=useState(false),[mapping,setMapping]=useState<Mapping>(presets.Generic),[preset,setPreset]=useState('Generic'),[endpoint,setEndpoint]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState<unknown>(null),[confirm,setConfirm]=useState(false),[deliveryId,setDeliveryId]=useState('');useEffect(()=>{try{const v=JSON.parse(localStorage.getItem('instaonpc_crm_mapping')||'null');if(v&&fields.every(k=>typeof v.mapping?.[k]==='string')){setMapping(v.mapping);setPreset(v.preset||'Custom');}}catch{}setReady(true);},[]);useEffect(()=>{if(ready)try{localStorage.setItem('instaonpc_crm_mapping',JSON.stringify({mapping,preset}));}catch{}},[mapping,preset,ready]);useEffect(()=>{setDeliveryId(crypto.randomUUID());setConfirm(false);},[assessment.id,mapping,endpoint]);
function csv(){try{download('instaonpc-'+preset.toLowerCase()+'-leads.csv',exportCSV([assessment],mapping),'text/csv;charset=utf-8');notify(`CSV download started · ${preset} mapping applied to all 11 columns.`);setOpen(false);}catch(e){notify((e as Error).message);}}
async function template(f?:File){if(!f)return;try{const headers=parseCSV(await f.text())[0];const guessed=guessHeaders(headers);let count=0;const next={...mapping};for(const k of fields)if(guessed[k]){next[k]=guessed[k];count++;}setMapping(next);setPreset('Custom');notify(`${count} of 11 fields matched. Review every column before export.`);}catch(e){notify((e as Error).message);}}
let payload:unknown;try{payload={schemaVersion:'1.0',event:'lead.assessed',eventId:deliveryId,generatedAt:assessment.createdAt,consultant:assessment.lead.agentName,reviewStatus:'draft',mapping:preset,fields:mappedValues(assessment,mapping)};}catch{payload={error:'Complete all 11 unique column titles first.'};}
async function send(test=false){setBusy(true);try{const r=await api('/api/webhook',test?{action:'test',payload:{schemaVersion:'1.0',event:'lead.created',eventId:deliveryId,lead:assessment.lead}}:{action:'dispatch',endpoint,deliveryId,payload,confirm});setResult(r);notify(test?'Test payload saved in the private ingestion feed.':r.receipt?.ok?'Webhook destination accepted the request.':'Webhook returned a non-success response; inspect the receipt.');}catch(e){setResult({error:(e as Error).message});}finally{setBusy(false);}}
return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger className="primary"><Download size={16}/> CRM export</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="crm-overlay"/><Dialog.Content className="crm-modal campaign"><div className="modal-header"><div><span className="eyebrow">DELIVERY / CONFIGURATION</span><Dialog.Title>Make it fit your CRM.</Dialog.Title><Dialog.Description>Match the 11 output columns to your import template.</Dialog.Description></div><Dialog.Close aria-label="Close CRM export"><X size={22}/></Dialog.Close></div><div className="modal-scroll"><div className="action-row">{Object.keys(presets).map(p=><button className={preset===p?'selected':''} key={p} onClick={()=>{setPreset(p);setMapping(presets[p]);}}>{p}</button>)}<label className="upload-button"><Upload size={15}/> Upload template CSV<input type="file" accept=".csv,text/csv" onChange={e=>template(e.target.files?.[0])}/></label></div><p className="subtle">{preset} mapping · Suggested headers. Custom CRM properties may need to be created in your CRM first.</p><div className="mapping-grid">{fields.map(k=><label key={k}><span>{presets.Generic[k]} <ArrowRight size={13}/></span><input value={mapping[k]} maxLength={100} onChange={e=>{setMapping({...mapping,[k]:e.target.value});setPreset('Custom');}}/></label>)}</div><div className="action-row"><button onClick={()=>{setMapping(presets.Generic);setPreset('Generic');}}><RotateCcw size={14}/> Reset defaults</button><button className="primary" onClick={csv}><Download size={15}/> Download CSV</button></div><section className="webhook-config"><span className="eyebrow">API WEBHOOK</span><h3>Review, then deliver.</h3><p className="subtle">External destinations must match FACTORY_WEBHOOK_ALLOWLIST. No credentials or response bodies are stored in the feed.</p><label>Destination endpoint<input type="url" placeholder="https://your-approved-crm.example/webhook" value={endpoint} onChange={e=>setEndpoint(e.target.value)}/></label><details><summary>Preview mapped JSON</summary><pre>{JSON.stringify(payload,null,2)}</pre></details><label className="check-label"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/> I reviewed the destination and payload and authorize this delivery.</label><div className="action-row"><button className="primary" disabled={busy||!confirm||!endpoint} onClick={()=>send()}><Send size={15}/> Push webhook payload</button><button disabled={busy} onClick={()=>send(true)}>Test local ingestion</button><button onClick={async()=>{try{setResult(await api('/api/webhook'));}catch(e){notify((e as Error).message);}}}>Refresh ingestion feed</button></div>{result!==null&&<pre className="response-console" aria-live="polite">{JSON.stringify(result,null,2)}</pre>}</section></div></Dialog.Content></Dialog.Portal></Dialog.Root>;}
