import { pgTable, varchar, timestamp, jsonb, customType } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import type { 
  ProjectStatus,
  BusinessProfile, 
  RevenueLeak, 
  Opportunity, 
  Offer, 
  SkillFile, 
  ContentAsset, 
  KPIBaseline, 
  FactLock, 
  ExportPackage 
} from '@/lib/types';

// Custom type for tsvector since Drizzle doesn't have native support for it in schema definition yet
const tsvector = customType<{ data: string }>({
  dataType() {
    return 'tsvector';
  },
});

export const projects = pgTable('projects', {
  id: varchar('id', { length: 255 }).primaryKey(),
  name: varchar('name', { length: 255 }).notNull(),
  status: varchar('status', { length: 50 }).$type<ProjectStatus>().notNull(),
  
  businessProfile: jsonb('business_profile').$type<BusinessProfile>(),
  revenueLeaks: jsonb('revenue_leaks').$type<RevenueLeak[]>(),
  opportunities: jsonb('opportunities').$type<Opportunity[]>(),
  selectedOpportunityId: varchar('selected_opportunity_id', { length: 255 }),
  offer: jsonb('offer').$type<Offer>(),
  skills: jsonb('skills').$type<SkillFile[]>(),
  contentAssets: jsonb('content_assets').$type<ContentAsset[]>(),
  kpiBaselines: jsonb('kpi_baselines').$type<KPIBaseline[]>(),
  factLocks: jsonb('fact_locks').$type<FactLock[]>(),
  exportPackage: jsonb('export_package').$type<ExportPackage>(),

  // This column will be generated by the database based on name and business profile fields
  // for full-text search. Drizzle push will create this as a generated column.
  searchVector: tsvector('search_vector').generatedAlwaysAs((): any => sql`
    setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
    setweight(to_tsvector('english', coalesce((business_profile->>'industry'), '')), 'B') ||
    setweight(to_tsvector('english', coalesce((business_profile->>'url'), '')), 'C')
  `),

  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export const auditLogs = pgTable('audit_logs', {
  id: varchar('id', { length: 255 }).primaryKey(),
  projectId: varchar('project_id', { length: 255 }),
  action: varchar('action', { length: 255 }).notNull(),
  target: varchar('target', { length: 255 }).notNull(),
  performedBy: varchar('performed_by', { length: 255 }).notNull(),
  details: varchar('details', { length: 1000 }),
  timestamp: timestamp('timestamp').notNull().defaultNow(),
});

