import { z } from 'zod';
export const leadSchema = z.object({
 businessName:z.string().trim().min(1).max(200), phone:z.string().max(100).default(''), address:z.string().max(500).default(''), city:z.string().max(150).default(''), website:z.string().max(1000).default(''), rating:z.string().max(10).default(''), reviews:z.string().max(16000).default(''), socials:z.string().max(2000).default(''), service:z.string().max(200).default('AI Front Desk + Local Lead Engine'), agentName:z.string().max(100).default('Devon'), introduction:z.string().max(2000).default(''), tone:z.enum(['Professional','Casual','Urgent']).default('Professional')
});
export type Lead = z.infer<typeof leadSchema>;
export const emptyLead:Lead={businessName:'',phone:'',address:'',city:'',website:'',rating:'',reviews:'',socials:'',service:'AI Front Desk + Local Lead Engine',agentName:'Devon',introduction:'',tone:'Professional'};
export const analysisSchema=z.object({strategy:z.string(),strengths:z.array(z.string()),technicalGaps:z.array(z.string()),serviceGaps:z.array(z.string()),outreachEmail:z.string(),voiceScript:z.string(),reviewSentiments:z.array(z.object({reviewIndex:z.number().int(),sentiment:z.enum(['Positive','Neutral','Negative'])})),evidenceNotes:z.array(z.string())});
export type Analysis=z.infer<typeof analysisSchema>;
export type Assessment={id:string;lead:Lead;analysis:Analysis;createdAt:string;mode:'openai'|'sample'};
export type BatchRow={id:string;lead:Lead;status:'pending'|'running'|'success'|'error';assessment?:Assessment;error?:string};
export type Batch={id:string;name:string;createdAt:string;rows:BatchRow[];revision:number};
export const fields=['businessName','address','city','phone','rating','website','socials','technicalGaps','serviceGaps','outreachEmail','voiceScript'] as const;
export type Mapping=Record<typeof fields[number],string>;
export const presets:Record<string,Mapping>={
 Generic:{businessName:'Business Name',address:'Address',city:'City',phone:'Phone',rating:'Rating',website:'Website',socials:'Social Profiles',technicalGaps:'Technical Gaps',serviceGaps:'Service Gaps',outreachEmail:'Outreach Email',voiceScript:'Voice Script'},
 HubSpot:{businessName:'Name',address:'Street Address',city:'City',phone:'Phone Number',rating:'Rating',website:'Company Domain Name',socials:'Social Profiles',technicalGaps:'Technical Gaps',serviceGaps:'Product Interest',outreachEmail:'Outreach Email',voiceScript:'Voice Script'},
 Salesforce:{businessName:'Name',address:'BillingStreet',city:'BillingCity',phone:'Phone',rating:'Rating',website:'Website',socials:'SocialProfiles',technicalGaps:'TechnicalGaps',serviceGaps:'ProductInterest',outreachEmail:'OutreachEmail',voiceScript:'VoiceScript'}
};
export function completeness(l:Lead){const parts=[['Business name',20,!!l.businessName.trim()],['Phone',15,!!l.phone.trim()],['Address',15,!!l.address.trim()],['City',10,!!l.city.trim()],['Website',10,!!l.website.trim()],['Rating',10,l.rating!==''&&Number.isFinite(Number(l.rating))&&Number(l.rating)>=0&&Number(l.rating)<=5],['Review text',15,!!l.reviews.trim()],['Social profiles',5,!!l.socials.trim()]] as const;return {score:parts.reduce((n,[,w,ok])=>n+(ok?w:0),0),parts};}
export function allOutputs(a:Assessment){return `${a.lead.businessName}\n${a.createdAt}\nDraft for human review · ${a.mode}\n\nSTRATEGIC ANALYSIS & GAPS\n${a.analysis.strategy}\n\nStrengths\n${a.analysis.strengths.join('\n')}\n\nTechnical gaps\n${a.analysis.technicalGaps.join('\n')}\n\nService gaps\n${a.analysis.serviceGaps.join('\n')}\n\nOUTREACH PROPOSAL\n${a.analysis.outreachEmail}\n\nPHONE / VOICE SCRIPT\n${a.analysis.voiceScript}\n\nEVIDENCE NOTES\n${a.analysis.evidenceNotes.join('\n')}`;}
export function reviewLines(lead:Lead){return lead.reviews.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,100);}
export function mappedValues(a:Assessment,m:Mapping){validateMapping(m);return Object.fromEntries(fields.map(k=>[m[k],k in a.lead?a.lead[k as keyof Lead]:a.analysis[k as keyof Analysis]]).map(([k,v])=>[k,Array.isArray(v)?v.join('; '):v]));}
export function validateMapping(m:Mapping){const vals=fields.map(k=>m[k]?.trim());if(vals.some(v=>!v)||new Set(vals.map(v=>v.toLowerCase())).size!==fields.length)throw new Error('All 11 column names must be nonempty and unique.');if(vals.some(v=>v.length>100||['__proto__','constructor','prototype'].includes(v)))throw new Error('Invalid column name.');}
export function csvCell(v:unknown){let s=String(v??'');if(/^[\s]*[=+\-@\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';}
export function exportCSV(items:Assessment[],m:Mapping){validateMapping(m);return '\ufeff'+[fields.map(k=>csvCell(m[k])).join(','),...items.map(a=>{const v=mappedValues(a,m);return fields.map(k=>csvCell(v[m[k]])).join(',');})].join('\r\n');}
export function parseCSV(text:string){if(text.length>500000)throw new Error('CSV must be under 500 KB.');const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(cell);cell='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(cell);if(row.some(x=>x.trim()))rows.push(row);row=[];cell='';}else cell+=c;}if(quoted)throw new Error('CSV contains an unclosed quote.');row.push(cell);if(row.some(x=>x.trim()))rows.push(row);if(rows[0])rows[0][0]=rows[0][0].replace(/^\ufeff/,'');if(rows.length>26)throw new Error('Use at most 25 leads per batch.');if(!rows.length)throw new Error('CSV is empty.');if(new Set(rows[0]).size!==rows[0].length)throw new Error('CSV headers must be unique.');return rows;}
export const aliases:Record<string,string[]>={businessName:['businessname','companyname','company','name'],phone:['phone','phonenumber'],address:['address','streetaddress','billingstreet'],city:['city','billingcity'],rating:['rating','reviewscore'],website:['website','url','companydomainname'],reviews:['reviews','feedback','reviewsummary'],socials:['socials','socialprofiles'],technicalGaps:['technicalgaps'],serviceGaps:['servicegaps','productinterest'],outreachEmail:['outreachemail','emailproposal'],voiceScript:['voicescript','phonescript']};
export function guessHeaders(headers:string[]){return Object.fromEntries(Object.entries(aliases).map(([k,names])=>[k,headers.find(h=>names.includes(h.toLowerCase().replace(/[^a-z]/g,'')))||'']));}
