// Durable storage for the private, single-operator Site. Never uses a hosted filesystem.
export async function database():Promise<import("@cloudflare/workers-types").D1Database>{const {env}=await import('cloudflare:workers');const db=(env as unknown as {DB?:import("@cloudflare/workers-types").D1Database}).DB;if(!db)throw new Error('Workspace database is unavailable.');return db;}
export async function initialize(){const db=await database();await db.batch([
 db.prepare('CREATE TABLE IF NOT EXISTS factory_documents (id TEXT PRIMARY KEY, kind TEXT NOT NULL, payload TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL)'),
 db.prepare('CREATE INDEX IF NOT EXISTS factory_documents_kind ON factory_documents(kind,updated_at)'),
 db.prepare('CREATE TABLE IF NOT EXISTS factory_locks (id TEXT PRIMARY KEY, expires INTEGER NOT NULL)'),
 db.prepare('CREATE TABLE IF NOT EXISTS factory_limits (id TEXT PRIMARY KEY, count INTEGER NOT NULL)')]);return db;}
export async function list<T>(kind:string):Promise<T[]>{const db=await initialize();const r=await db.prepare('SELECT payload FROM factory_documents WHERE kind=? ORDER BY updated_at DESC LIMIT 200').bind(kind).all<{payload:string}>();return r.results.map(x=>JSON.parse(x.payload));}
export async function get<T>(id:string,kind?:string):Promise<T|undefined>{const db=await initialize();const r=await db.prepare('SELECT payload FROM factory_documents WHERE id=? AND (? IS NULL OR kind=?)').bind(id,kind||null,kind||null).first<{payload:string}>();return r?JSON.parse(r.payload):undefined;}
export async function put(id:string,kind:string,value:unknown){const db=await initialize();await db.prepare('INSERT INTO factory_documents(id,kind,payload,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,revision=factory_documents.revision+1,updated_at=excluded.updated_at').bind(id,kind,JSON.stringify(value),new Date().toISOString()).run();}
export async function insert(id:string,kind:string,value:unknown){const db=await initialize();const r=await db.prepare('INSERT OR IGNORE INTO factory_documents(id,kind,payload,updated_at) VALUES(?,?,?,?)').bind(id,kind,JSON.stringify(value),new Date().toISOString()).run();return r.meta.changes>0;}
export async function remove(id:string,kind:string){const db=await initialize();await db.prepare('DELETE FROM factory_documents WHERE id=? AND kind=?').bind(id,kind).run();}
export async function clear(kind:string){const db=await initialize();await db.prepare('DELETE FROM factory_documents WHERE kind=?').bind(kind).run();}
export async function acquire(id:string,seconds=120){const db=await initialize();const now=Date.now();const r=await db.prepare('INSERT INTO factory_locks(id,expires) VALUES(?,?) ON CONFLICT(id) DO UPDATE SET expires=excluded.expires WHERE factory_locks.expires<?').bind(id,now+seconds*1000,now).run();return r.meta.changes>0;}
export async function release(id:string){const db=await initialize();await db.prepare('DELETE FROM factory_locks WHERE id=?').bind(id).run();}
export async function rateLimit(bucket:string,limit=30){const db=await initialize();const hour=Math.floor(Date.now()/3600000);const id=bucket+':'+hour;const row=await db.prepare('INSERT INTO factory_limits(id,count) VALUES(?,1) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count').bind(id).first<{count:number}>();if(!row||row.count>limit)throw new Error('Hourly request limit reached. Try again later.');}
export async function sitesEnabled(){try{const {env}=await import('cloudflare:workers');return !!(env as unknown as {DB?:unknown}).DB;}catch{if(process.env.FACTORY_HOST==="sites")throw new Error("The Site database binding is unavailable.");return false;}}
